import asyncio
from web3 import Web3
from config import RPC_URL, CHAIN_ID

class BlockchainMonitor:
    """
    Handles all Web3/Alchemy RPC interactions for status checks and Merging prep.
    Uses async Web3 to avoid blocking the main event loop.
    """
    def __init__(self):
        # Use a non-async HTTPProvider for Web3 setup (assuming standard Web3)
        self.w3 = Web3(Web3.HTTPProvider(RPC_URL)) 
        
        # We need a separate async client for robust async calls (not standard Web3)
        # NOTE: For true async, you would use async Web3.py libraries. 
        # For simplicity/compatibility, we use Web3.py sync methods here, 
        # but in production, these must be run in a separate thread/process or async lib.
        
        if not self.w3.is_connected():
            raise ConnectionError(f"Cannot connect to Polygon RPC at {RPC_URL}")
        
        print(f"[Monitor] Connected to Polygon RPC. Chain ID: {self.w3.eth.chain_id}")

    # --- STATUS CHECK ---
    
    def get_block_number(self):
        """eth_blockNumber - Checks connection and returns latest block."""
        return self.w3.eth.block_number

    # --- FEE & GAS MANAGEMENT ---

    def estimate_gas_for_tx(self, tx_params):
        """
        eth_estimateGas - Estimates gas needed for a specific transaction (like a Merge).
        :param tx_params: Dictionary containing 'from', 'to', 'data', 'value'
        :returns: Estimated gas amount (in Wei)
        """
        # Note: tx_params would be dynamically generated by the Strategist before calling Merge
        return self.w3.eth.estimate_gas(tx_params)

    def get_fee_history(self, num_blocks=5, percentiles=[25, 75]):
        """
        eth_feeHistory - Fetches base fee and reward history for block selection.
        :param num_blocks: Number of blocks to look back (0x5 = 5 blocks)
        :param percentiles: Percentiles for the priority fee (e.g., 20, 30)
        :returns: Dictionary of historical fee data.
        """
        # The w3.eth.fee_history method handles the JSON-RPC call translation
        return self.w3.eth.fee_history(
            self.w3.to_hex(num_blocks), 
            'latest', 
            percentiles
        )

    # --- TRANSACTION LOGS & RECEIPTS ---

    def get_block_receipts(self, block_identifier='latest'):
        """
        eth_getBlockReceipts - Fetches all receipts in a given block.
        Used to quickly check if our Merge transaction was included.
        """
        # Note: Web3.py does not have a direct eth_getBlockReceipts wrapper, 
        # so this is a custom JSON-RPC call via the provider.
        return self.w3.provider.make_request("eth_getBlockReceipts", [block_identifier])


    def get_logs(self, from_block, to_block, address=None, topics=None):
        """
        eth_getLogs - Queries logs (events) matching address and topics.
        Used to track OrderFilled and Merge events on Polymarket contracts.
        """
        # Example addresses (Polymarket CTF Exchange, USDC, etc.) and Topics (event signatures)
        filter_params = {
            "fromBlock": from_block,
            "toBlock": to_block,
            "address": address,
            "topics": topics
        }
        return self.w3.eth.get_logs(filter_params)